### ISSUE TITLE
prisma generate not working in Termux

### ISSUE THREAD

**Issue by DebiprasadXD** [XDBots/LazyBot#1]
While trying to use LazyBot in Termux , I get this error.

$ prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Unable to require(`/data/data/com.termux/files/home/LazyBot/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
 dlopen failed: "/data/data/com.termux/files/home/LazyBot/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

**Comment by ArnabXD** [comment]
prisma already has an [issue](https://github.com/prisma/prisma/issues/9968) opened for the exact same error.

Let's see if I can get any ETA or workaround from them .

**Comment by DebiprasadXD** [comment]
I see

**Comment by DebiprasadXD** [comment]
@ArnabXD I came to notice that the version of node is creating conflict with prisma.
To overcome this issue we have to install 12.22.5 verison of node

Commands : 
`proot-distro login ubuntu` (I have used ubuntu if you have used any other distro just modify command according to it)

#Update packages
`apt update`

#uninstall newer verison of nodejs,node
`npm uninstall nodejs`
`npm uninstall node`

#install older version of nodejs and mainly npm
`apt install nodejs`
`apt install npm`

after that check the verison of node by `node -v`
if it's v12.22.5 you are good to go.

if it does not show this verison just do `npm uninstall node` again and `exit `

login again
now the `node`
then `require("os").platform()` will return linux instead of android.
Hopefully this will solve this issue of prisma generator.

**Comment by ArnabXD** [comment]
Wait does this actually work ? I had no idea we can do that 😮 .

>#uninstall newer verison of nodejs,node
npm uninstall nodejs
npm uninstall node

**Comment by DebiprasadXD** [comment]
> Wait does this actually work ? I had no idea we can do that 😮 .
> 
> > #uninstall newer verison of nodejs,node
> > npm uninstall nodejs
> > npm uninstall node

without doing that we can't switch to older version of node as I tested.

**Comment by ArnabXD** [comment]
You don't have nodejs by default so why downgrade. whatever , I don't wanna go deep in those.
node v12 two steps behind from current LTS. So not a preferred way. 

LazyBot can use a different ORM at this point. Working with Prisma was fun and easy.

**Comment by DebiprasadXD** [comment]
yeah it was a bad idea (I'm not good with nodejs) to use that much old but atleast we're able troubleshoot it , looking forward to new different ideas you put through your repos :D
